version: "3.3"

services:
  go-postgres:
    image: postgres:15-alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./.env_docker
    volumes:
       - ./data:/var/lib/postgresql/data
       - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: .
    restart: always
    ports:
      - 8080:8080
