version: "3.3"

services:
  go-postgres:
    image: postgres:15-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: 
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    volumes:
       - ./data:/var/lib/postgresql/data
       - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: .
    ports:
      - 8080:8080
