info:
  contact: {}
paths:
  /api/adduser/{id}:
    post:
      consumes:
      - application/json
      description: Add new user with info
      parameters:
      - description: User name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
      summary: Add new user
      tags:
      - Users
  /api/getuser/{id}:
    get:
      consumes:
      - application/json
      description: Get user details by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Get user by ID
      tags:
      - Users
swagger: "2.0"
